package com.redhat.evaluacioncrediticia;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(4c4744f90685ff5485be1bb7a4b9d586)
 */
@org.kie.api.definition.type.Label(value = "Oferta Productos")
public class Oferta extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Importe Maximo")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Double montoMaximo;
    
    @org.kie.api.definition.type.Label(value = "Producto")
    @org.kie.api.definition.type.Position(value = 1)
    private com.redhat.evaluacioncrediticia.Producto producto;
    
    @org.kie.api.definition.type.Label(value = "Prsopecto")
    @org.kie.api.definition.type.Position(value = 0)
    private com.redhat.evaluacioncrediticia.Prospecto prospecto;

    public Oferta() {
    }

    public Oferta(com.redhat.evaluacioncrediticia.Prospecto prospecto, com.redhat.evaluacioncrediticia.Producto producto, java.lang.Double montoMaximo) {
        this.prospecto = prospecto;
        this.producto = producto;
        this.montoMaximo = montoMaximo;
    }


    
    public java.lang.Double getMontoMaximo() {
        return this.montoMaximo;
    }

    public void setMontoMaximo(java.lang.Double montoMaximo) {
        this.montoMaximo = montoMaximo;
    }
    
    public com.redhat.evaluacioncrediticia.Producto getProducto() {
        return this.producto;
    }

    public void setProducto(com.redhat.evaluacioncrediticia.Producto producto) {
        this.producto = producto;
    }
    
    public com.redhat.evaluacioncrediticia.Prospecto getProspecto() {
        return this.prospecto;
    }

    public void setProspecto(com.redhat.evaluacioncrediticia.Prospecto prospecto) {
        this.prospecto = prospecto;
    }
}