package com.redhat.evaluacioncrediticia;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(9a71b786d3bd0f4e17f84478ebfe6495)
 */
@org.kie.api.definition.type.Label(value = "Prospecto")
public class Prospecto extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Calificacion Crediticia SBS")
    @org.kie.api.definition.type.Position(value = 9)
    private java.lang.Integer calificacionSbs;
    
    @org.kie.api.definition.type.Label(value = "Central Risgo")
    @org.kie.api.definition.type.Position(value = 10)
    private java.util.List<com.redhat.evaluacioncrediticia.CentralRiesgo> centralRiesgo;
    
    @org.kie.api.definition.type.Label(value = "Num Documento Identidad")
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.String docNum;
    
    @org.kie.api.definition.type.Label(value = "Edad")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer edad;
    
    @org.kie.api.definition.type.Label(value = "Estado Civil")
    @org.kie.api.definition.type.Position(value = 8)
    private java.lang.Character estadoCivil;
    
    @org.kie.api.definition.type.Label(value = "Genero")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Character genero;
    
    @org.kie.api.definition.type.Label(value = "Id Documento Identidad")
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Integer idDoc;
    
    @org.kie.api.definition.type.Label(value = "Importe Maximo Endeudamiento")
    @org.kie.api.definition.type.Position(value = 13)
    private java.lang.Double maxEndeudamiento;
    
    @org.kie.api.definition.type.Label(value = "Nivel Cliente")
    @org.kie.api.definition.type.Position(value = 12)
    private java.lang.Integer nivelCliente;
    
    @org.kie.api.definition.type.Label(value = "Nombre")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String nombre;
    
    @org.kie.api.definition.type.Label(value = "Numero Dependientes")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Integer numDependientes;
    
    @org.kie.api.definition.type.Label(value = "Dependencia Laboral")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.Character relacionDependencia;
    
    @org.kie.api.definition.type.Label(value = "Ingreso Anual")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Double salario;
    
    @org.kie.api.definition.type.Label(value = "Total Deuda Calculada")
    @org.kie.api.definition.type.Position(value = 11)
    private java.lang.Double totalDeuda;

    public Prospecto() {
    }

    public Prospecto(java.lang.String nombre, java.lang.Double salario, java.lang.Integer edad, java.lang.Character genero, java.lang.Integer numDependientes, java.lang.Character relacionDependencia, java.lang.Integer idDoc, java.lang.String docNum, java.lang.Character estadoCivil, java.lang.Integer calificacionSbs, java.util.List<com.redhat.evaluacioncrediticia.CentralRiesgo> centralRiesgo, java.lang.Double totalDeuda, java.lang.Integer nivelCliente, java.lang.Double maxEndeudamiento) {
        this.nombre = nombre;
        this.salario = salario;
        this.edad = edad;
        this.genero = genero;
        this.numDependientes = numDependientes;
        this.relacionDependencia = relacionDependencia;
        this.idDoc = idDoc;
        this.docNum = docNum;
        this.estadoCivil = estadoCivil;
        this.calificacionSbs = calificacionSbs;
        this.centralRiesgo = centralRiesgo;
        this.totalDeuda = totalDeuda;
        this.nivelCliente = nivelCliente;
        this.maxEndeudamiento = maxEndeudamiento;
    }


    
    public java.lang.Integer getCalificacionSbs() {
        return this.calificacionSbs;
    }

    public void setCalificacionSbs(java.lang.Integer calificacionSbs) {
        this.calificacionSbs = calificacionSbs;
    }
    
    public java.util.List<com.redhat.evaluacioncrediticia.CentralRiesgo> getCentralRiesgo() {
        return this.centralRiesgo;
    }

    public void setCentralRiesgo(java.util.List<com.redhat.evaluacioncrediticia.CentralRiesgo> centralRiesgo) {
        this.centralRiesgo = centralRiesgo;
    }
    
    public java.lang.String getDocNum() {
        return this.docNum;
    }

    public void setDocNum(java.lang.String docNum) {
        this.docNum = docNum;
    }
    
    public java.lang.Integer getEdad() {
        return this.edad;
    }

    public void setEdad(java.lang.Integer edad) {
        this.edad = edad;
    }
    
    public java.lang.Character getEstadoCivil() {
        return this.estadoCivil;
    }

    public void setEstadoCivil(java.lang.Character estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    
    public java.lang.Character getGenero() {
        return this.genero;
    }

    public void setGenero(java.lang.Character genero) {
        this.genero = genero;
    }
    
    public java.lang.Integer getIdDoc() {
        return this.idDoc;
    }

    public void setIdDoc(java.lang.Integer idDoc) {
        this.idDoc = idDoc;
    }
    
    public java.lang.Double getMaxEndeudamiento() {
        return this.maxEndeudamiento;
    }

    public void setMaxEndeudamiento(java.lang.Double maxEndeudamiento) {
        this.maxEndeudamiento = maxEndeudamiento;
    }
    
    public java.lang.Integer getNivelCliente() {
        return this.nivelCliente;
    }

    public void setNivelCliente(java.lang.Integer nivelCliente) {
        this.nivelCliente = nivelCliente;
    }
    
    public java.lang.String getNombre() {
        return this.nombre;
    }

    public void setNombre(java.lang.String nombre) {
        this.nombre = nombre;
    }
    
    public java.lang.Integer getNumDependientes() {
        return this.numDependientes;
    }

    public void setNumDependientes(java.lang.Integer numDependientes) {
        this.numDependientes = numDependientes;
    }
    
    public java.lang.Character getRelacionDependencia() {
        return this.relacionDependencia;
    }

    public void setRelacionDependencia(java.lang.Character relacionDependencia) {
        this.relacionDependencia = relacionDependencia;
    }
    
    public java.lang.Double getSalario() {
        return this.salario;
    }

    public void setSalario(java.lang.Double salario) {
        this.salario = salario;
    }
    
    public java.lang.Double getTotalDeuda() {
        return this.totalDeuda;
    }

    public void setTotalDeuda(java.lang.Double totalDeuda) {
        this.totalDeuda = totalDeuda;
    }
}